# This is a basic workflow to help you get started with Actions

name: Windows-CRD

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Authorization Code'
        required: true
      pincode:
        description: 'PIN Code'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initializing Setup
      run: ./setup.ps1

    - name: Starting CRD 
      run: |
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="${{ github.event.inputs.authcode }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=${Env:COMPUTERNAME} -pin=${{ github.event.inputs.pincode }}

    # Add more steps if necessary
    - name: Keep Alive
      # Add the appropriate command or script to keep the workflow alive

# Add more configurations or steps as needed
